// LISTS
export const SET_LISTS = "SET_LISTS";
export const SET_LIST = "SET_LIST";
export const UPDATE_LIST = "UPDATE_LIST";
export const REMOVE_LIST = "REMOVE_LIST";

// PRODUCTS
export const SET_PRODUCTS = "SET_PRODUCTS";
export const CHANGE_USER_PRODUCT = 'CHANGE_USER_PRODUCT';
export const ADD_USER_PRODUCT = 'ADD_USER_PRODUCT';
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_PRODUCT_STATE = "CHANGE_PRODUCT_STATE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

// USERS
export const AUTH_USER = "AUTH_USER";

// FRIENDS
export const SET_FRIENDS = "SET_FRIENDS";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
