// LISTS
export const SET_LISTS = "SET_LISTS";
export const SET_LIST = "SET_LIST";
export const UPDATE_LIST = "UPDATE_LIST";
export const REMOVE_LIST = "REMOVE_LIST";

// PRODUCTS
export const SET_PRODUCTS = "SET_PRODUCTS";
export const CHANGE_USER_PRODUCT = 'CHANGE_USER_PRODUCT';
export const ADD_USER_PRODUCT = 'ADD_USER_PRODUCT';
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_PRODUCT_STATE = "CHANGE_PRODUCT_STATE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

// USERS
export const AUTH_USER = "AUTH_USER";
export const CHANGE_REG_LOGIN = 'CHANGE_REG_LOGIN';
export const LOGIN_USER = 'LOGIN_USER';

// ERRORS
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAN_ERRORS ='CLEAN_ERRORS';
